[package]
name = "tls-certificate-exporter"
version = "0.0.0"
authors = ["Leo Chen <leo881003@gmail.com>"]
edition = "2021"
rust-version = "1.71.0"
description = "A Prometheus exporter to scrape certificates from remote connections to monitor the certificates."
repository = "https://github.com/Leo1003/tls-certificate-exporter"
license = "Apache-2.0"
# TODO: Set keywords and categories before the first publish
keywords = []
categories = []

[dependencies]
