targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[bans]
deny = [
    # serde_derive includes pre-compiled binaries in 1.0.172 ~ 1.0.183
    { name = "serde_derive", version = ">= 1.0.172, < 1.0.184" }
]

[advisories]
vulnerability = "deny"
unmaintained = "warn"
notice = "warn"
unsound = "deny"
ignore = [
    "RUSTSEC-2020-0071",
]

[licenses]
unlicensed = "warn"
allow-osi-fsf-free = "neither"
copyleft = "deny"
unused-allowed-license = "allow"
allow = [
    "Apache-2.0",
    "MIT",
    "ISC",
    "MPL-2.0",
    "BSD-3-Clause",
    "Unicode-DFS-2016",
]
exceptions = [
    { allow = ["Unicode-DFS-2016"], name = "unicode-ident" },
    { allow = ["OpenSSL"], name = "ring" },
]

[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 }
]
